# Generated by Django 5.0.3 on 2024-03-30 04:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('task1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Marks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maths', models.FloatField()),
                ('physics', models.FloatField()),
                ('chemistry', models.FloatField()),
                ('english', models.FloatField()),
                ('hindi', models.FloatField()),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='task1.student')),
            ],
        ),
    ]
