# Generated by Django 5.0.3 on 2024-04-01 05:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marks', '0002_alter_marks_student'),
        ('task1', '0002_alter_student_roll'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marks',
            name='student',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='task1.student'),
        ),
    ]
