# Generated by Django 4.2.8 on 2024-02-19 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeExperience',
            fields=[
                ('ID', models.BigAutoField(primary_key=True, serialize=False)),
                ('company_name', models.CharField(max_length=100)),
                ('role', models.CharField(max_length=70)),
                ('date_of_joining', models.DateField()),
                ('last_date', models.DateField()),
            ],
        ),
    ]
