# Generated by Django 5.0.3 on 2024-04-03 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task1', '0003_studentcategory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentcategory',
            name='student',
        ),
        migrations.AddField(
            model_name='student',
            name='category',
            field=models.ManyToManyField(to='task1.studentcategory'),
        ),
    ]
