# Generated by Django 4.2.8 on 2024-02-26 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='demo',
        ),
    ]
