# Generated by Django 4.2.8 on 2024-02-26 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_rename_teams_team'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='facebook_link',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='team',
            name='twitter_link',
            field=models.CharField(),
        ),
    ]
