# Generated by Django 4.2.8 on 2024-02-17 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_api', '0002_rename_phoneno_employee_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('ID', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('roll', models.IntegerField()),
                ('city', models.CharField(max_length=70)),
            ],
        ),
        migrations.DeleteModel(
            name='Employee',
        ),
    ]
