# Generated by Django 4.2.8 on 2024-02-17 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='phoneno',
            new_name='phone',
        ),
    ]
