# Generated by Django 5.0.3 on 2024-04-03 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task1', '0002_alter_student_roll'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100)),
                ('student', models.ManyToManyField(to='task1.student')),
            ],
        ),
    ]
