# Generated by Django 4.2.8 on 2024-04-25 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_jwt', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='role_name',
            field=models.CharField(default=1, max_length=70),
            preserve_default=False,
        ),
    ]
