# Generated by Django 4.2.8 on 2024-01-25 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('student_ID', models.BigAutoField(primary_key=True, serialize=False)),
            ],
        ),
    ]
