# Generated by Django 4.2.8 on 2024-02-22 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('token_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='passby',
            field=models.CharField(default='aditya', max_length=70),
            preserve_default=False,
        ),
    ]
