# Generated by Django 4.2.8 on 2024-02-22 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('token_app', '0002_student_passby'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='passby',
        ),
    ]
