# Generated by Django 4.2.8 on 2024-01-28 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='marks',
            name='student_name',
            field=models.CharField(default='default', max_length=70),
            preserve_default=False,
        ),
    ]
