# Generated by Django 4.2.8 on 2024-01-28 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marks', '0002_marks_student_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='marks',
            name='student_name',
        ),
    ]
