# Generated by Django 4.2.8 on 2024-01-28 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marks', '0003_remove_marks_student_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='marks_settings',
            fields=[
                ('marks_settings_ID', models.IntegerField(primary_key=True, serialize=False)),
                ('passing_percentage', models.FloatField()),
                ('passing_marks_per_subject', models.FloatField()),
            ],
        ),
        migrations.AddField(
            model_name='marks',
            name='failed_subjects',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
    ]
