# Generated by Django 4.2.8 on 2024-01-29 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marks', '0005_alter_marks_settings_passing_marks_per_subject_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='marks_settings',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='marks_settings',
            name='marks_settings_ID',
            field=models.IntegerField(default=1),
        ),
    ]
