# Generated by Django 4.2.8 on 2024-01-29 04:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marks', '0006_marks_settings_id_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='marks_settings',
            new_name='MarksSettings',
        ),
    ]
