# Generated by Django 4.2.8 on 2024-01-29 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marks', '0007_rename_marks_settings_markssettings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='marks',
            name='Total_marks_per_subject',
        ),
        migrations.AddField(
            model_name='markssettings',
            name='Total_marks_per_subject',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
