# Generated by Django 4.2.8 on 2024-01-29 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marks', '0009_remove_marks_failed_subjects'),
    ]

    operations = [
        migrations.AddField(
            model_name='marks',
            name='Student_name',
            field=models.CharField(default=0, max_length=70),
            preserve_default=False,
        ),
    ]
