# Generated by Django 4.2.8 on 2024-01-30 12:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
        ('marks', '0010_marks_student_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marks',
            name='Student_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marks', to='student.student'),
        ),
    ]
