# Generated by Django 4.2.8 on 2024-02-14 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='image',
            field=models.ImageField(default=11, upload_to='images/'),
            preserve_default=False,
        ),
    ]
