# Generated by Django 4.2.8 on 2024-02-14 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_student_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='image',
        ),
    ]
