# Generated by Django 4.2.8 on 2024-01-08 06:32

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='core',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='default/download.png', max_length=255, upload_to=core.models.core.image_upload_to)),
            ],
        ),
    ]
